steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--rm', '--privileged', 'multiarch/qemu-user-static', '--reset', '-p', 'yes']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--use']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['login', '-u', '$DOCKERHUB_USERNAME', '-p', '$DOCKERHUB_TOKEN']
    env:
      - 'DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME'
      - 'DOCKERHUB_TOKEN=$DOCKERHUB_TOKEN'
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "RELEASE=0.2" > /workspace/.env
        echo "DOCKER_HUB_USERNAME=$DOCKERHUB_USERNAME" >> /workspace/.env
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'bake', '-f', 'docker-bake.hcl', '--push']
options:
  machineType: 'E2_HIGHCPU_32'
  diskSizeGb: '200'

substitutions:
  _DOCKERHUB_USERNAME: ""  # 사용자 정의 대체 변수 정의
  _DOCKERHUB_TOKEN: ""     # 사용자 정의 대체 변수 정의