name: Docker Image Build and Release

on:
  push:
    paths:
      - ".github/workflows/base.yml"
      - "builds/base/docker-bake.hcl"
      - "builds/base/Dockerfile"
      - "builds/shared/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-base:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: Setup Docker
        uses: ./.github/actions/docker-setup
        id: setup
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base images
        uses: docker/bake-action@v6
        env:
          BUILDX_BAKE_ENTITLEMENTS_FS: 0
        with:
          source: .
          files: |
            builds/shared/versions.hcl
            builds/base/docker-bake.hcl
          push: true
          set: |
            ${{ steps.setup.outputs.is-production != 'true' && format('*.args.RELEASE_VERSION={0}', steps.setup.outputs.release-suffix) || '' }}

