name: Base Image Build and Release

on:
  push:
    paths:
      - ".github/workflows/base.yml"
      - "official-templates/base/**"
      - "official-templates/pytorch/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: blacksmith-8vcpu-ubuntu-2204
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear space to remove unused folders
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: useblacksmith/build-push-action@v1.2
        with:
          setup-only: true
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Determine if this is a production build
        id: build_type
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "is_production=true" >> $GITHUB_OUTPUT
          else
            echo "is_production=false" >> $GITHUB_OUTPUT
          fi

      - name: Get changed files
        id: changed_files
        uses: tj-actions/changed-files@v46
        with:
          files_yaml: |
            base:
              - official-templates/base/**
            pytorch:
              - official-templates/pytorch/**

      - name: Set Environment Variables
        if: steps.build_type.outputs.is_production != 'true'
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##refs/heads/} | sed 's/\//-/g')
          echo "RELEASE=dev-${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Determine build files
        id: build_files
        run: |
          BUILD_FILES=()
          
          # If base changed, build both base and pytorch
          if [[ "${{ steps.changed_files.outputs.base_any_changed }}" == "true" ]]; then
            BUILD_FILES+=("official-templates/base/docker-bake.hcl")
            BUILD_FILES+=("official-templates/pytorch/docker-bake.hcl")
          # If only pytorch changed, build only pytorch
          elif [[ "${{ steps.changed_files.outputs.pytorch_any_changed }}" == "true" ]]; then
            BUILD_FILES+=("official-templates/pytorch/docker-bake.hcl")
          fi
          
          if [ ${#BUILD_FILES[@]} -gt 0 ]; then
            BUILD_FILES_CSV=$(IFS=,; echo "${BUILD_FILES[*]}")
            echo "files=${BUILD_FILES_CSV}" >> $GITHUB_OUTPUT
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push images
        if: steps.build_files.outputs.should_build == 'true'
        uses: docker/bake-action@v6
        env:
          BUILDX_BAKE_ENTITLEMENTS_FS: 0
        with:
          source: .
          files: |
            official-templates/shared/versions.hcl
            ${{ steps.build_files.outputs.files }}
          push: true
          set: |
            ${{ steps.build_type.outputs.is_production != 'true' && format('*.args.RELEASE={0}', env.RELEASE) || '' }}
            *.args.GITHUB_WORKSPACE=${{ github.workspace }}