name: Build and Push Containers

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Trigger Google Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml \
            --substitutions _DOCKERHUB_USERNAME="${{ vars.DOCKERHUB_USERNAME }}",_DOCKERHUB_TOKEN="${{ secrets.DOCKERHUB_TOKEN }}" .